name: browser-extension

on:
  pull_request:
  push:
    branches: [main]

jobs:
  extension-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: browser-extension
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v4
      with: 
        package_json_file: "browser-extension/package.json"
    - uses: actions/setup-node@v6
      with:
        node-version-file: "browser-extension/package.json"
        cache-dependency-path: "browser-extension/pnpm-lock.yaml"
        cache: pnpm
    - name: Install dependencies
      run: pnpm install

    - name: Lint
      run: pnpm lint

    - name: Complie
      run: pnpm compile

    - name: Format
      run: pnpm format:check

    - name: Test
      run: pnpm test
