name: browser-extension

on:
  pull_request:
  push:
    branches: [main]

jobs:
  extension-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: browser-extension
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "browser-extension/package.json"
      - uses: actions/setup-node@v6
        with:
          node-version-file: "browser-extension/package.json"
          cache-dependency-path: "browser-extension/pnpm-lock.yaml"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Complie
        run: pnpm compile

      - name: Format
        run: pnpm format:check

      - name: Test
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: browser-extension
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "browser-extension/package.json"
      - uses: actions/setup-node@v6
        with:
          node-version-file: "browser-extension/package.json"
          cache-dependency-path: "browser-extension/pnpm-lock.yaml"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build extension zip
        run: pnpm zip
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: bth-extension.zip
          path: browser-extension/.output/bth-extension-*.zip
          retention-days: 30

      - uses: "marvinpinto/action-automatic-releases@1.2.1"
        if: github.ref == 'refs/heads/master'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "bth-extension-latest"
          prerelease: true
          title: "Extension Development Build"
          files: browser-extension/.output/bth-extension-*.zip

  e2e-tests:
    defaults:
      run:
        working-directory: browser-extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "browser-extension/package.json"
      - uses: actions/setup-node@v6
        with:
          node-version-file: "browser-extension/package.json"
          cache-dependency-path: "browser-extension/pnpm-lock.yaml"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium
      - name: Build extension
        run: pnpm build

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run E2E tests
        working-directory: ./browser-extension
        run: xvfb-run pnpm test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: browser-extension/playwright-report/
          retention-days: 30
